# Generated by Django 2.2.5 on 2019-09-07 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristspots',
            name='attractions',
            field=models.ManyToManyField(to='attractions.Attractions'),
        ),
    ]
