# Generated by Django 2.2.5 on 2019-09-07 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
        ('evaluations', '0001_initial'),
        ('core', '0002_touristspots_attractions'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristspots',
            name='comments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comments.Comments'),
        ),
        migrations.AddField(
            model_name='touristspots',
            name='evaluations',
            field=models.ManyToManyField(to='evaluations.Evaluations'),
        ),
    ]
