# Generated by Django 2.2.5 on 2019-09-07 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
        ('core', '0003_auto_20190907_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristspots',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='addresses.Addresses'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='touristspots',
            name='comments',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='comments.Comments'),
            preserve_default=False,
        ),
    ]
