# Generated by Django 2.2.5 on 2019-09-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
        ('core', '0004_auto_20190907_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touristspots',
            name='comments',
        ),
        migrations.AddField(
            model_name='touristspots',
            name='comments',
            field=models.ManyToManyField(to='comments.Comments'),
        ),
    ]
