# Generated by Django 2.2.5 on 2019-09-07 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190907_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristspots',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='addresses.Addresses'),
        ),
    ]
