# Generated by Django 2.2.5 on 2019-09-10 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190907_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristspots',
            name='picture',
            field=models.ImageField(default=1, upload_to='', verbose_name='tourist_spots'),
            preserve_default=False,
        ),
    ]
