# Generated by Django 2.2.5 on 2019-09-07 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attractions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('opening_hours', models.TimeField()),
                ('minimum_age', models.IntegerField()),
            ],
        ),
    ]
