# Generated by Django 2.2.5 on 2019-09-10 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attractions',
            name='picture',
            field=models.ImageField(default=1, upload_to='', verbose_name='attractions'),
            preserve_default=False,
        ),
    ]
